apiVersion: apps/v1
kind: Deployment
metadata:
  name: drandtest-deployment
  labels:
    app: drandtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drandtest
  template:
    metadata:
      labels:
        app: drandtest
    spec:
      containers:
      - name: drandtest-contianer
        image: ghcr.io/drand/go-drand:{{.Values.tag}}
        command: ["drand", "start", "--verbose", "--private-listen", "0.0.0.0:8080", "--public-listen", "0.0.0.0:9080", "--tls-disable"] 
        ports:
        - containerPort: 8080 # 指定容器内的端口号
        - containerPort: 9080 # 指定容器内的度量指标端口号
        - containerPort: 8888 # 指定容器内的控制端口号
        volumeMounts:
          - name: drandtest-home
            mountPath: "/root/.drand"
      volumes:
        - name: drandtest-home
          persistentVolumeClaim:
            claimName: drandtest-home
