apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: drandtest-kenlabs-org-certificate
spec:
  secretName: drandtest-kenlabs-org-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - drandtest.kenlabs.org
