apiVersion: apps/v1
kind: Deployment
metadata:
  name: drand-deployment
  labels:
    app: drand
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drand
  template:
    metadata:
      labels:
        app: drand
    spec:
      containers:
      - name: drand-contianer
        image: drandorg/go-drand:{{.Values.tag}}
        command: ["start", "--verbose", "--private-listen", "0.0.0.0:8080", "--public-listen", "0.0.0.0:9080", "--tls-disable"] 
        # --cert-dir "/data/drand/.drand/tls_certificates" --tls-cert "/data/drand/.drand/tls_keypair/cert.pem" --tls-key "/data/drand/.drand/tls_keypair/key.pem"
        ports:
        - containerPort: 8080 # 指定容器内的端口号
        - containerPort: 9080 # 指定容器内的度量指标端口号
        - containerPort: 8888 # 指定容器内的控制端口号
          volumeMounts:
            - name: drand-home
              mountPath: "/root/.drand"
      volumes:
        - name: drand-home
          persistentVolumeClaim:
            claimName: drand-home
