apiVersion: apps/v1
kind: Deployment
metadata:
  name: drand-deployment
  labels:
    app: drand
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drand
  template:
    metadata:
      labels:
        app: drand
    spec:
      containers:
      - name: drand-container
        image: gitdatateam/drand:v1.5.11
        ports:
        - containerPort: 8080 # 指定容器内的端口号
        - containerPort: 9999 # 指定容器内的度量指标端口号
        - containerPort: 8888 # 指定容器内的控制端口号
          volumeMounts:
            - name: drand-home
              mountPath: "/root/.drand"
      volumes:
        - name: drand-home
          persistentVolumeClaim:
            claimName:drand-home