apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: drand-ingress
  annotations:
    meta.helm.sh/release-name: drand-ingress
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
  labels:
    apptype: drand-ingress
    app.kubernetes.io/managed-by: Helm
    heritage: Helm
    release:  drand-ingress
spec:
  ingressClassName: {{.Values.ingress_name}}
  rules:
  - host: drand.kenlabs.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: drand-service
            port:
              number: 8080 # 指定Service的端口号
